# Generated by Django 5.2 on 2025-08-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='attempted_questions',
            field=models.PositiveIntegerField(default=0, help_text='Number of questions actually attempted by the student'),
        ),
    ]
