# Generated by Django 5.2 on 2025-08-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='document',
            name='processing_status',
        ),
    ]
